### ISSUE TITLE
Label Printer

### ISSUE THREAD

**Issue by fhwac** [AudioVisionaryMusic/Varemodtagelse#1]
@crishoj @jrishoj 
Jeg har talt med HM og de vil bruge en printer de selv har brugt meget. En Datamax O'Neil classII A-4310.
Jeg har vedhæftet datasheet på den her.
[AClassMII.pdf](https://github.com/AudioVisionaryMusic/Varemodtagelse/files/1841313/AClassMII.pdf)
Umildbart kan den ikke æde pdf men den må ligne meget Citizen udprint. Den æder Zebra og billeder og bar.
Jeg har også vedhæftet programmers manual for classII printere hvis det kan bruges.
[DPL Class Series II programmers manual.pdf](https://github.com/AudioVisionaryMusic/Varemodtagelse/files/1841315/DPL.Class.Series.II.programmers.manual.pdf)

**Comment by crishoj** [comment]
This issue was moved to AudioVisionaryMusic/gate#103
